services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.halvorteigen.no
    volumes:
      - ./apps/homepage/config:/app/config
      - ./apps/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - homelab-docker
    ports:
      - 3000:3000

networks:
  homelab-docker:
    name: homelab-docker
    external: true