services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.halvorteigen.no
    volumes:
      - ./apps/homepage/config:/app/config
      - ./apps/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - homelab-docker
    healthcheck:
      test:
        ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/healthcheck || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

networks:
  homelab-docker:
    name: homelab-docker
    external: true
