services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - homelab-docker

networks:
  homelab-docker:
    name: homelab-docker
    external: true
