version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/apps/*"
    groups:
      n8n-and-runners:
        patterns:
          - "n8nio/n8n"
          - "n8nio/runners"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
