version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/apps/*"
    schedule:
      interval: "hourly"
