---
- Social:
    - GitHub:
        - icon: si-github
          href: https://github.com/halvorot
          description: GitHub profile
    - LinkedIn:
        - icon: si-linkedin
          href: https://www.linkedin.com/in/halvor-teigen/
          description: LinkedIn profile