---
- Developer:
    - Github:
        - icon: si-github
          href: https://github.com/halvorot

- Social:
    - LinkedIn:
        - icon: si-linkedin
          href: https://www.linkedin.com/in/halvor-teigen/
          description: Halvor Ødegård Teigen's LinkedIn profile