title: Halvor Ødegård Teigen's Homelab
favicon: h-logo.svg

layout:
  My Applications:
    style: column
    columns: 3
  Hosted Applications:
    style: column
    columns: 3
  Infrastructure & Management:
    style: column
    columns: 3

headerStyle: clean
theme: dark
