- datetime:
    format:
      timeStyle: short
      dateStyle: long
      hourCycle: h23

- greeting:
    text: "Welcome back, Halvor"
    italic: true

- resources:
    cpu: true
    memory: true
    disk: /

- docker:
    label: Containers
    server: my-docker

- search:
    provider: google
    focus: true
    showSearchSuggestions: true
