services:
  voiceboard-server:
    container_name: voiceboard-server
    image: ghcr.io/halvorot/speech-to-whiteboard-server:sha-e64fc4b
    restart: unless-stopped
    environment:
      - SUPABASE_URL=${VOICEBOARD_SUPABASE_URL}
      - DATABASE_URL=${VOICEBOARD_DATABASE_URL}
      - DEEPGRAM_API_KEY=${VOICEBOARD_DEEPGRAM_API_KEY}
      - GROQ_API_KEY=${VOICEBOARD_GROQ_API_KEY}
      - PORT=8080
    networks:
      - homelab-docker
  voiceboard:
    container_name: voiceboard
    image: ghcr.io/halvorot/speech-to-whiteboard-client:sha-e64fc4b
    restart: unless-stopped
    depends_on:
      - voiceboard-server
    networks:
      - homelab-docker

networks:
  homelab-docker:
    name: homelab-docker
    external: true
