services:
  voiceboard-api:
    container_name: voiceboard-api
    image: ghcr.io/halvorot/speech-to-whiteboard-server:latest
    restart: unless-stopped
    env:
      - SUPABASE_URL=${VOICEBOARD_SUPABASE_URL}
      - DATABASE_URL=${VOICEBOARD_DATABASE_URL}
      - DEEPGRAM_API_KEY=${VOICEBOARD_DEEPGRAM_API_KEY}
      - GROQ_API_KEY=${VOICEBOARD_GROQ_API_KEY}
      - PORT=8080
    networks:
      - homelab-docker
  voiceboard:
    container_name: voiceboard
    image: ghcr.io/halvorot/speech-to-whiteboard-client:latest
    restart: unless-stopped
    depends_on:
      - voiceboard-api
    networks:
      - homelab-docker

networks:
  homelab-docker:
    name: homelab-docker
    external: true
