
services:
  app:
    container_name: nocobase
    image: nocobase/nocobase:2.1.6-full
    restart: always
    networks:
      - homelab-docker
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Application key, used to generate user tokens, etc.
      # If APP_KEY is changed, old tokens will become invalid
      # Can be any random string, and ensure it is not leaked
      - APP_KEY=${NOCOBASE_APP_KEY:-nocobase}
      # Database type, supports postgres, mysql, mariadb
      - DB_DIALECT=postgres
      # Database host, can be replaced with an existing database server IP
      - DB_HOST=postgres
      # Database port
      - DB_PORT=5432
      # Database name
      - DB_DATABASE=${NOCOBASE_DB_DATABASE:-nocobase}
      # Database user
      - DB_USER=${NOCOBASE_DB_USER:-nocobase}
      # Database password
      - DB_PASSWORD=${NOCOBASE_DB_PASSWORD:-nocobase}
      # Timezone, please change it to your local timezone, e.g., America/New_York
      - TZ=${NOCOBASE_TZ:-Europe/Oslo}

    volumes:
      - /srv/data/nocobase/storage:/app/nocobase/storage
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:80', (res) => process.exit(res.statusCode < 500 ? 0 : 1)).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    # init: true

  postgres:
    container_name: nocobase-postgres
    image: postgres:18.4
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: ${NOCOBASE_DB_USER:-nocobase}
      POSTGRES_DB: ${NOCOBASE_DB_DATABASE:-nocobase}
      POSTGRES_PASSWORD: ${NOCOBASE_DB_PASSWORD:-nocobase}
    volumes:
      - /srv/data/nocobase/storage/db/postgres:/var/lib/postgresql
    networks:
      - homelab-docker
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h 127.0.0.1 -p 5432 -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  homelab-docker:
    name: homelab-docker
    external: true
