services:
  coder:
    image: ghcr.io/coder/coder:2.37.2
    container_name: coder
    restart: unless-stopped
    group_add:
      - "990"
    environment:
      CODER_ACCESS_URL: https://coder.halvorteigen.no
      CODER_WILDCARD_ACCESS_URL: "*-coder.halvorteigen.no"
      CODER_HTTP_ADDRESS: 0.0.0.0:7080
      CODER_PG_CONNECTION_URL: "postgresql://coder:${CODER_POSTGRES_PASSWORD:?CODER_POSTGRES_PASSWORD is required}@coder-database/coder?sslmode=disable"
      CODER_DERP_FORCE_WEBSOCKETS: "true"
      CODER_DISABLE_PATH_APPS: "true"
      CODER_DISABLE_PASSWORD_AUTH: "false"
      CODER_DISABLE_WORKSPACE_SHARING: "true"
      CODER_EXPERIMENTS: oauth2,mcp-server-http
      CODER_EXTERNAL_AUTH_GITHUB_DEFAULT_PROVIDER_ENABLE: "false"
      CODER_EXTERNAL_TOKEN_ENCRYPTION_KEYS: ${CODER_EXTERNAL_TOKEN_ENCRYPTION_KEY:?CODER_EXTERNAL_TOKEN_ENCRYPTION_KEY is required}
      CODER_OAUTH2_GITHUB_ALLOW_EVERYONE: "true"
      CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS: "false"
      CODER_OAUTH2_GITHUB_CLIENT_ID: ${CODER_OAUTH2_GITHUB_CLIENT_ID:?CODER_OAUTH2_GITHUB_CLIENT_ID is required}
      CODER_OAUTH2_GITHUB_CLIENT_SECRET: ${CODER_OAUTH2_GITHUB_CLIENT_SECRET:?CODER_OAUTH2_GITHUB_CLIENT_SECRET is required}
      CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE: "false"
      CODER_OAUTH2_GITHUB_DEVICE_FLOW: "false"
      CODER_MAX_TOKEN_LIFETIME: 8760h
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab-docker
      - coder-backend
    depends_on:
      coder-database:
        condition: service_healthy

  coder-database:
    image: postgres:18
    container_name: coder-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: coder
      POSTGRES_PASSWORD: ${CODER_POSTGRES_PASSWORD:?CODER_POSTGRES_PASSWORD is required}
      POSTGRES_USER: coder
    volumes:
      - /srv/data/coder/postgres:/var/lib/postgresql
    networks:
      - coder-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coder -d coder"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  homelab-docker:
    name: homelab-docker
    external: true
  coder-backend:
    internal: true
