services:
  winelottery:
    container_name: winelottery
    image: ghcr.io/halvorot/wine-lottery-website:20250324180437
    restart: unless-stopped
    networks:
      - homelab-docker
    environment:
      - VITE_SUPABASE_URL=https://amwivjkqhskhzbauzwcj.supabase.co
      - VITE_SUPABASE_PUBLISHABLE_KEY=sb_publishable_4DjJpPOeJPDZ7EUaudu1XA_VJJ40tyO

networks:
  homelab-docker:
    name: homelab-docker
    external: true
