services:
  winelottery:
    container_name: winelottery
    image: ghcr.io/halvorot/wine-lottery-website:20260615131530
    restart: unless-stopped
    networks:
      - homelab-docker

networks:
  homelab-docker:
    name: homelab-docker
    external: true
